redis:
  mem_limit: 128000000
  image: redis:3.0-alpine
  command: redis-server
  ports:
    - 6379
api:
  mem_limit: 256000000
  build: .
  command: serve-docker
  links:
    - redis
  ports:
    - 8000:8000
  volumes:
     - ./sqlite:/var/lib/sqlite/data
  environment:
    LOG_LEVEL: INFO
    FLOWROUTE_ACCESS_KEY: YOUR_FLOWROUTE_ACCESS_KEY
    FLOWROUTE_SECRET_KEY: YOUR_FLOWROUTE_ACCESS_KEY
    FLOWROUTE_NUMBER: YOUR_FLOWROUTE_TELEPHONE_NUMBER
    ORG_NAME: Flowroute
    CELERY_BROKER_URL: redis://redis:6379
    CELERY_RESULT_BACKEND: redis://redis:6379
celery:
  mem_limit: 256000000
  build: .
  command: celery_worker
  volumes:
     - ./sqlite:/var/lib/sqlite/data
  links:
    - redis
  environment:
    LOG_LEVEL: INFO
    FLOWROUTE_ACCESS_KEY: YOUR_FLOWROUTE_ACCESS_KEY
    FLOWROUTE_SECRET_KEY: YOUR_FLOWROUTE_ACCESS_KEY
    FLOWROUTE_NUMBER: YOUR_FLOWROUTE_TELEPHONE_NUMBER
    ORG_NAME: Flowroute
    CELERY_BROKER_URL: redis://redis:6379
    CELERY_RESULT_BACKEND: redis://redis:6379
