version: '2'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server
    volumes:
      - redis:/var/lib/redis/data
    ports:
      - '6379:6379'

  api:
    build: .
    command: serve
    ports:
      - '8000:8000'
    volumes:
      - sqlite:/var/lib/sqlite
    env_file: ./env

  celery:
    build: .
    command: celery_worker
    volumes:
      - sqlite:/var/lib/sqlite
    links:
      - redis
    env_file: ./env

volumes:
  redis:
  sqlite:
