redis:
  mem_limit: 128000000
  image: redis:3.0-alpine
  command: redis-server
  ports:
    - 6379
api:
  mem_limit: 256000000
  build: .
  command: serve
  links:
    - redis
  ports:
    - 8000:8000
  volumes:
     - ./sqlite:/var/lib/sqlite/data
  environment:
    LOG_LEVEL: INFO
    FLOWROUTE_ACCESS_KEY: foo
    FLOWROUTE_SECRET_KEY: bar
    FLOWROUTE_NUMBER: 11111111111
    ORG_NAME: Flowroute
celery:
  mem_limit: 256000000
  build: .
  command: celery_worker
  volumes:
     - ./sqlite:/var/lib/sqlite/data
  links:
    - redis
  environment:
    LOG_LEVEL: INFO
    FLOWROUTE_ACCESS_KEY: foo
    FLOWROUTE_SECRET_KEY: bar
    FLOWROUTE_NUMBER: 11111111111
    ORG_NAME: Flowroute
