redis:
  mem_limit: 128000000
  image: redis:3.0-alpine
  command: redis-server
  volumes:
    - /var/lib/redis/data:/var/lib/redis/data
  ports:
    - 6379
api:
  mem_limit: 256000000
  build: .
  command: serve
  links:
    - redis
  ports:
    - 8000:8000
  volumes:
     - /var/lib/sqlite/data:/var/lib/sqlite/data
  environment:
    LOG_LEVEL: INFO
celery:
  mem_limit: 256000000
  build: .
  command: celery_worker
  volumes:
    - /var/lib/sqlite/data:/var/lib/sqlite/data
  links:
    - redis
  environment:
    LOG_LEVEL: INFO
